### ISSUE TITLE
Firmware v3.9 fails L-band receive with custom hardware

### ISSUE THREAD

**Issue by edgecase14** [sparkfun/SparkFun_RTK_Firmware#756] opened 2024-02-17 21:22 UTC
### Subject of the issue
 The usb serial or BT console spews 

`zedEnableLBandCorrections: Unknown platform`
`zedEnableLBandCorrections: Unknown platform`
`zedEnableLBandCorrections: Unknown platform`

continuously, and endlessly, and an RTK Float or Fix isn't obtained after 5  to 10 minutes.

### Your workbench
This is a bare ESP32 Thing Plus C connected to ZED-F9P/NEO-D9S combo breakout.

### Steps to reproduce
After reset to firmware defaults, and configure WiFI and custom Thingstream token, and provision keys.  Firmware v3.8 works as expected, with valid L-band keys, an RTK fix is obtained.  
Then upgrade to  v3.9, and once keys are available, which since we are using a custom Thingstream profile, requires to Disable then Enable PointPerfect due to a pending issue, the spewing begins.

### Expected behavior
RTK Fix should happen after 2 minutes.

### Actual behavior
RTK fix never obtained, and endless console messages.

**Comment by PaulZC** [comment] 2024-06-13 10:27
I am closing this. It may be possible to convince the firmware that it is running on a Facet L-Band, but you would need to make sure that you are replicating the hardware correctly - including all IO pin connections. The "Unknown platform" error is caused by the lack of the "DEVICE_SENSE" ID resistor divider on IO pin 35.

Best wishes,
Paul

**Closed by PaulZC** 2024-06-13 10:27 UTC
