### ISSUE TITLE
Lost data

### ISSUE THREAD

**Issue by pyrog** [sparkfun/SparkFun_RTK_Firmware#37] opened 2021-06-14 13:15 UTC
### Subject of the issue
* Some coordinates are incomplete.
* Some data are missing.

Here a digit is lost in 7.1012131, 4.7285551. The real coordinates are **4**7.1012131, 4.7285551.
<img width=33% src="https://user-images.githubusercontent.com/2158081/121891906-5a23b500-cd1c-11eb-85bb-36e3285c5482.png">

After adding the missing digit, the track is correct:
<img width=33% src="https://user-images.githubusercontent.com/2158081/121891997-77f11a00-cd1c-11eb-9f65-7a73c303ee5d.jpg">

Here 4 and 3 measurements have missing data (fix type for 2, coordinates for 5):
<img valign=top width=33% src="https://user-images.githubusercontent.com/2158081/121893284-13cf5580-cd1e-11eb-949f-a65eed5f53dc.png">  <img valign=top width=33% src="https://user-images.githubusercontent.com/2158081/121893666-8a6c5300-cd1e-11eb-8466-25856e65523e.png">  <img valign=top width=33% src="https://user-images.githubusercontent.com/2158081/121893728-9bb55f80-cd1e-11eb-8cb9-0172d352acc7.png">

Here red dots have missing fix type:
<img valign=top width=33% src="https://user-images.githubusercontent.com/2158081/121894940-0024ee80-cd20-11eb-813e-99ce60327d67.png">  <img valign=top width=33%  src="https://user-images.githubusercontent.com/2158081/121895148-32cee700-cd20-11eb-8bc9-53fd685584f9.png"> <img valign=top width=33% src="https://user-images.githubusercontent.com/2158081/121895780-e59f4500-cd20-11eb-81fe-7055738b78c7.png">

### Your workbench
* rtkFirmwareVersion=v1.3-Jun  4 2021
* device connected over Bluetooth with several apps that transmitting RTCM 3 back to the device
* everything being powered by USB
* default settings [SFE_Surveyor_Settings.txt](https://github.com/sparkfun/SparkFun_RTK_Firmware/files/6648283/SFE_Surveyor_Settings.txt) (NMEA only)

**Comment by pyrog** [comment] 2021-06-14 13:46
Sample [bretagne.nmea](https://github.com/sparkfun/SparkFun_RTK_Firmware/files/6648664/bretagne.nmea.txt) loaded in JOSM
- 27 coordinates imported
- 1 malformed sentence
- 6 checksum errors

<img width=50% src="https://user-images.githubusercontent.com/2158081/121901823-09658980-cd27-11eb-875f-f39cf8197955.png">
<img width="305" alt="Capture d’écran 2021-06-14 à 15 44 32" src="https://user-images.githubusercontent.com/2158081/121902230-6c572080-cd27-11eb-918a-9438e5eaa5b5.png">

**Comment by nseidle** [comment] 2021-06-14 15:12
This looks like a duplicate of [issue 30](https://github.com/sparkfun/SparkFun_RTK_Firmware/issues/30). Please add notes to that issue when possible.

**Closed by nseidle** 2021-06-14 15:12 UTC
